#pragma once
#include <io/serial.h>
#include <stdint.h>
#include <stddef.h>
#include <system/sysinfo.h>
#include <system/macros.h>
#include <system/pfa.h>
#include <screen/graphics.h>
#include <string.h>